packages:
  - .

onlyBuiltDependencies:
  - esbuild

blockExoticSubdeps: true
frozenLockfile: true
minimumReleaseAge: 4320
savePrefix: ''
strictDepBuilds: true
strictPeerDependencies: true
trustPolicy: no-downgrade
